### ISSUE TITLE
Cannot compile on Mac OS X 10.10.4

### ISSUE THREAD

**Issue by duguyue100** [teradeep/demo-apps#3]
Hi,

I'm trying to compile the linux camera on Mac OS X 10.10.4, however my compiler keep reporting me:

```
gcc -O3 -c -fpic -Wall -I. -I/usr/local/include -I/Users/dgyHome/torch/install/include linuxcamera.c
In file included from linuxcamera.c:17:0:
videocap.h:4:29: fatal error: linux/videodev2.h: No such file or directory
compilation terminated.
make: *** [linuxcamera.o] Error 1
```

I understand that there is no such folder as `/usr/include/linux` on Mac, is there a way to have a workaround? Do I need to install any package for having `videodev2.h`?

Regards,
Hu Yuhuang.

**Comment by mvitez** [comment]
Linux camera is for Linux. You need the "camera" package for Mac. Install it with
luarocks install camera

**Comment by duguyue100** [comment]
This is also what I thought in the first place. After I installed camera and I try to run the program by `qlua run.lua`.

Then I run into this error:
```
Number of threads used:	1
/Users/dgyHome/torch/install/share/lua/5.1/xlua/init.lua:351: module 'camopencv' not found:
	no field package.preload['camopencv']
	no file './camopencv.lua'
	no file '/Users/dgyHome/torch/install/share/luajit-2.1.0-alpha/camopencv.lua'
	no file '/usr/local/share/lua/5.1/camopencv.lua'
	no file '/usr/local/share/lua/5.1/camopencv/init.lua'
	no file '/Users/dgyHome/torch/install/share/lua/5.1/camopencv.lua'
	no file '/Users/dgyHome/torch/install/share/lua/5.1/camopencv/init.lua'
	no file './camopencv.so'
	no file '/usr/local/lib/lua/5.1/camopencv.so'
	no file '/Users/dgyHome/torch/install/lib/lua/5.1/camopencv.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
warning: <camopencv> could not be loaded (is it installed?)
qlua: /Users/dgyHome/torch/install/share/lua/5.1/xlua/init.lua:312: failed to load camopencv wrapper: verify that camopencv is installed
stack traceback:
	[C]: at 0x0107e341d0
	[C]: in function 'error'
	/Users/dgyHome/torch/install/share/lua/5.1/xlua/init.lua:312: in function 'error'
	/Users/dgyHome/torch/install/share/lua/5.1/camera/init.lua:21: in main chunk
	[C]: in function 'require'
	./frame.lua:25: in function 'prep_lua_camera'
	./frame.lua:82: in function 'init'
	run.lua:102: in main chunk
```

there seems no package named `camopencv` in luarocks package list

**Comment by duguyue100** [comment]
or I need to install OpenCV on my computer?

**Comment by culurciello** [comment]
yes you do not need opencv:
on OS X: "brew install opencv"
on ubuntu: "sudo apt-get install opencv"

**Comment by mvitez** [comment]
This I don't know, sorry, I don't have a Mac.

**Comment by codeAC29** [comment]
Yes you need to install OpenCV. At least thats what worked for me.

**Comment by duguyue100** [comment]
OK, now it's working, thanks you all!

**Comment by Rich700000000000** [comment]
Hey, I'm getting the same error as duguyue100, but I have opencv installed. What could be the problem?
